import { Task } from '../types/task';

export const tasks: Task[] = [
  // Individual tasks
  {
    id: '1',
    title: 'Make Your Bed Like a Superhero! 🦸‍♂️',
    assignedTo: 'user1',
    visibleTime: {
      start: '07:00',
      end: '09:00',
    },
    tokens: 20,
    timeSlot: 'morning',
    status: 'pending',
    requiresApproval: true,
  },
  {
    id: '2',
    title: 'Brush Teeth Adventure ✨',
    assignedTo: 'user2',
    visibleTime: {
      start: '07:30',
      end: '08:30',
    },
    tokens: 15,
    timeSlot: 'morning',
    status: 'pending',
    requiresApproval: false,
  },
  {
    id: '3',
    title: 'Get Dressed for Adventure 👕',
    assignedTo: 'user3',
    visibleTime: {
      start: '07:30',
      end: '08:30',
    },
    tokens: 15,
    timeSlot: 'morning',
    status: 'pending',
    requiresApproval: false,
  },
  {
    id: '4',
    title: 'Homework Power Hour 📚',
    assignedTo: 'user1',
    visibleTime: {
      start: '15:00',
      end: '17:00',
    },
    tokens: 50,
    timeSlot: 'afternoon',
    status: 'pending',
    requiresApproval: true,
  },
  {
    id: '5',
    title: 'Piano Practice 🎹',
    assignedTo: 'user2',
    visibleTime: {
      start: '15:00',
      end: '16:00',
    },
    tokens: 30,
    timeSlot: 'afternoon',
    status: 'pending',
    requiresApproval: true,
  },

  // Group tasks
  {
    id: '6',
    title: 'Family Dinner Time 🍽️',
    assignedTo: ['user1', 'user2', 'user3'],
    visibleTime: {
      start: '18:00',
      end: '19:00',
    },
    tokens: 25,
    timeSlot: 'evening',
    status: 'pending',
    requiresApproval: true,
    isGroupTask: true,
  },
  {
    id: '7',
    title: 'Clean Up Kitchen Together 🧹',
    assignedTo: ['user1', 'user2'],
    visibleTime: {
      start: '19:00',
      end: '19:30',
    },
    tokens: 30,
    timeSlot: 'evening',
    status: 'pending',
    requiresApproval: true,
    isGroupTask: true,
  },
  {
    id: '8',
    title: 'Storytime Adventure 📖',
    assignedTo: ['user2', 'user3'],
    visibleTime: {
      start: '20:00',
      end: '20:30',
    },
    tokens: 20,
    timeSlot: 'night',
    status: 'pending',
    requiresApproval: false,
    isGroupTask: true,
  },
  {
    id: '9',
    title: 'Brush Teeth Before Bed ✨',
    assignedTo: 'user1',
    visibleTime: {
      start: '20:10',
      end: '20:30',
    },
    tokens: 15,
    timeSlot: 'night',
    status: 'pending',
    requiresApproval: false,
  },
  {
    id: '10',
    title: 'Pajama Party Prep 🌙',
    assignedTo: 'user2',
    visibleTime: {
      start: '20:30',
      end: '21:00',
    },
    tokens: 15,
    timeSlot: 'night',
    status: 'pending',
    requiresApproval: false,
  },
  {
    id: '11',
    title: 'Reading Time 📘',
    assignedTo: 'user3',
    visibleTime: {
      start: '20:30',
      end: '21:00',
    },
    tokens: 15,
    timeSlot: 'night',
    status: 'pending',
    requiresApproval: false,
  },
];
